# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute on passengers if entity @s[tag=aj.blueprint.data] unless data entity @s {data:{rigHash: 'dbbdac3f54df6817bc04898ded7451ff272e6e2a4c365cbb3dfe16b20da15faa'}} on vehicle run function animated_java:blueprint/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1