# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.locator.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator8.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator7.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator6.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator5.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator12.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator11.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator10.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator9.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator16.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator15.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator14.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator13.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator20.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator19.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator18.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator17.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator24.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator23.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator22.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator21.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator2.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator3.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.locator4.uuid
function animated_java:blueprint/zzz/execute with storage aj:temp